### PR TITLE
Add eclipse project

### PR DESCRIPTION
**Pull request by ElectricRCAircraftGuy**
This PR adds an Eclipse project so that the entire Arduino source code, including the Arduino core, can easily be browsed--same as in a professional project.

### CODE REVIEW

**Comment by ElectricRCAircraftGuy** [comment]
NOTE THAT THIS PR ONLY EDITS LIKE 9 FILES, DESPITE IT SAYING IT EDITS LIKE 224 FILES. YOU MUST ACCEPT PR #18 first in order for the comparison to look correct, so please merge PR #18 and then look at this PR.

**Comment by nimrod46** [comment]
@ElectricRCAircraftGuy Thanks so much for your contributions, I will merge this PR once the conflict is solved.

**Comment by ElectricRCAircraftGuy** [comment]
Conflicts resolved; ready for review. See "AmboVent/3-Software/Arduino/readme.md" for a description of the new files, and see "AmboVent/3-Software/Arduino/arduino_core/readme.md" for a description of how to link in the Arduino core for browsing in Eclipse.

**Comment by ElectricRCAircraftGuy** [comment]
I've rebased onto your latest master and force pushed to resolve conflicts. It is ready to merge again.

**Comment by ElectricRCAircraftGuy** [comment]
I also checked to make sure it still builds, and it does:
```
Sketch uses 18412 bytes (59%) of program storage space. Maximum is 30720 bytes.
Global variables use 1046 bytes (51%) of dynamic memory, leaving 1002 bytes for local variables. Maximum is 2048 bytes.
```

**Pull request merged**
